# Generated by Django 4.2 on 2025-06-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketing", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriber",
            options={"ordering": ["-subscribed_at"]},
        ),
        migrations.RenameField(
            model_name="subscriber",
            old_name="created_at",
            new_name="subscribed_at",
        ),
        migrations.AddField(
            model_name="subscriber",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
